name: Networks
authors: [Sefiraat, mmmjjkx]
description: Edited by mmmjjkx. Thank you Slimefun.
main: io.github.sefiraat.networks.Networks
website: https://github.com/lijinhong11/Networks-Exp
version: ${project.version}
api-version: 1.20
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - Netheopoiesis
  - SlimeHUD
  - WildChests
commands:
  networks:
    description: /networks
    usage: /networks <sub>